version: "2"
services:
  sock-frontend:
    image: making/sockshop-frontend:latest
    ports:
    - 8080:8080
    mem_limit: 256m
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_WEB: DEBUG
      JAVA_OPTS: -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo
      BPL_JVM_THREAD_COUNT: 20
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      SOCK_CATALOGURL: http://sock-catalog:5001
      SOCK_CARTURL: http://sock-cart:5005
      SOCK_ORDERURL: http://sock-order:5004
      SOCK_PAYMENTURL: http://sock-payment:5002
      SOCK_SHIPPINGURL: http://sock-shipping:5003
    depends_on:
    - zipkin
  sock-catalog:
    image: making/sockshop-catalog:latest
    mem_limit: 256m
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_WEB: DEBUG
      LOGGING_LEVEL_LOL_MAKI_SOCKS: DEBUG
      SERVER_TOMCAT_THREADS_MAX: 4
      JAVA_OPTS: -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo
      BPL_JVM_THREAD_COUNT: 20
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sock_catalog
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
    depends_on:
    - mysql
    - zipkin
  sock-cart:
    image: making/sockshop-cart:latest
    mem_limit: 256m
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_WEB: DEBUG
      LOGGING_LEVEL_LOL_MAKI_SOCKS: DEBUG
      SERVER_TOMCAT_THREADS_MAX: 4
      JAVA_OPTS: -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo
      BPL_JVM_THREAD_COUNT: 20
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sock_cart
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
    depends_on:
    - mysql
    - zipkin
  sock-order:
    image: making/sockshop-order:latest
    mem_limit: 256m
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_WEB: DEBUG
      LOGGING_LEVEL_LOL_MAKI_SOCKS: DEBUG
      SERVER_TOMCAT_THREADS_MAX: 4
      JAVA_OPTS: -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo
      BPL_JVM_THREAD_COUNT: 20
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sock_order
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      SOCK_CARTURL: http://sock-cart:5005
      SOCK_PAYMENTURL: http://sock-payment:5002
      SOCK_SHIPPINGURL: http://sock-shipping:5003
    depends_on:
    - mysql
    - zipkin
  sock-payment:
    image: making/sockshop-payment:latest
    mem_limit: 256m
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_WEB: DEBUG
      LOGGING_LEVEL_LOL_MAKI_SOCKS: DEBUG
      SERVER_TOMCAT_THREADS_MAX: 4
      JAVA_OPTS: -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo
      BPL_JVM_THREAD_COUNT: 20
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sock_payment
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
    depends_on:
    - mysql
    - zipkin
  sock-shipping:
    image: making/sockshop-shipping:latest
    mem_limit: 256m
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_WEB: DEBUG
      LOGGING_LEVEL_LOL_MAKI_SOCKS: DEBUG
      SERVER_TOMCAT_THREADS_MAX: 4
      JAVA_OPTS: -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo
      BPL_JVM_THREAD_COUNT: 20
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sock_shipping
      SPRING_ZIPKIN_ENABLED: "true"
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
    depends_on:
    - mysql
    - zipkin
  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
    - 9411:9411