#@data/values
---
mysql_hostname: sock-catalog-mysql.sock-catalog.svc.cluster.local
mysql_port: "3306"
mysql_username: sockshop
mysql_password: sockshop
mysql_database: sock_catalog
sock_issuer_url:
wavefront_uri: https://wavefront.surf
wavefront_api_token:
wavefront_application_name: spring-socks