name: catalog-api
on:
  push:
    paths:
    - 'catalog-api/**'
    branches:
    - master
  pull_request:
    paths:
    - 'catalog-api/**'
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '14.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn package
      run: |
        set -ex
        ./mvnw -V package -f catalog-api/pom.xml -U
    - name: mvn spring-boot:build-image
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: making/sockshop-catalog
      run: |
        set -e
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        set +e
        docker pull ${IMAGE_NAME}
        set -e
        ./mvnw -V spring-boot:build-image -f catalog-api/pom.xml -Dspring-boot.build-image.imageName=${IMAGE_NAME} -Dmaven.test.skip=true
        docker push ${IMAGE_NAME}
